### ISSUE TITLE
HTTP2::Client.new throws ArgumentError (wrong number of arguments (given 1, expected 0)) on Ruby 3.0

### ISSUE THREAD

**Issue by rgaufman** [igrigorik/http-2#158]
I'm getting this:

```
irb(main):001:0> require 'http/2'
=> true
irb(main):002:0> conn = HTTP2::Client.new
Traceback (most recent call last):
        9: from /opt/homebrew/opt/ruby/bin/irb:23:in `<main>'
        8: from /opt/homebrew/opt/ruby/bin/irb:23:in `load'
        7: from /opt/homebrew/Cellar/ruby/3.0.0_1/lib/ruby/gems/3.0.0/gems/irb-1.3.0/exe/irb:11:in `<top (required)>'
        6: from (irb):2:in `<main>'
        5: from (irb):2:in `new'
        4: from /opt/homebrew/lib/ruby/gems/3.0.0/gems/http-2-0.10.2/lib/http/2/client.rb:28:in `initialize'
        3: from /opt/homebrew/lib/ruby/gems/3.0.0/gems/http-2-0.10.2/lib/http/2/connection.rb:79:in `initialize'
        2: from /opt/homebrew/lib/ruby/gems/3.0.0/gems/http-2-0.10.2/lib/http/2/connection.rb:79:in `new'
        1: from /opt/homebrew/lib/ruby/gems/3.0.0/gems/http-2-0.10.2/lib/http/2/compressor.rb:333:in `initialize'
ArgumentError (wrong number of arguments (given 1, expected 0))
```

This is my environment
```
Romans-MacBook-Pro-2.local ➜  bin  ruby --version
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin20]
Romans-MacBook-Pro-2.local ➜  bin  gem --version net-http2
3.2.3
Romans-MacBook-Pro-2.local ➜  bin  uname -a
Darwin Romans-MacBook-Pro-2.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101 arm64
```

Any ideas?

**Comment by piotaixr** [comment]
It seems related to the way Ruby 3 handles named parameters. The issue seems fixed on master with https://github.com/igrigorik/http-2/pull/156

**Comment by alextwoods** [comment]
@igrigorik  - any idea when this fix will get released as a new gem version?  The AWS SDK for Ruby currently breaks with the latest gem version of http-2 on Ruby 3.0, but I've confirmed all our tests pass when using the latest from master.

**Comment by igrigorik** [comment]
New release is live, this should be resolved. Please reopen if you run into any other issues!
